name: ZAP-Scan
on: [push]

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://bwapp.hakhub.net'
          artifact_name: sai-zap  # ZAP uploads this artifact for you
