name: ZAP Scan

on: [push]

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://bwapp.hakhub.net'
          docker_options: '--user 0'   # removes the YAML warning

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v3
        with:
          name: zap_scan               
          path: |
            report_html.html
            report_md.md
            report_json.json
